#!/bin/sh

CLOJURESCRIPT_HOME=clojurescript

CLASSPATH=src/clj:$CLOJURESCRIPT_HOME"/src/clj":$CLOJURESCRIPT_HOME"/src/cljs"

OUTPUT=web/ftree.js

for next in lib/*; do
  CLASSPATH=$CLASSPATH:$next
done

REPL_CLJ="(use 'cljs.closure)(def opts {:output-to \"$OUTPUT\" :output-dir \".out\" :optimizations :advanced :externs [\"src/externs.js\"]})(build \"src/cljs\" opts)"

# compile
java -server -cp "$CLASSPATH" clojure.main -e "$REPL_CLJ"
